spring.application.name=report-service
server.port=${REPORT_SERVICE_PORT:8085}

spring.datasource.url=jdbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:1433};databaseName=${DB_NAME:ArizaNetDb};encrypt=true;trustServerCertificate=true
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:ArizaNet123!}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false

jwt.secret=${JWT_SECRET:arizanet_secret_key_for_auth_service_2026}

springdoc.swagger-ui.path=/swagger-ui.html